-- ส่วนที่ 2: สร้างตารางทั้งหมด
SET search_path TO public;
BEGIN;

-- สร้างตารางต่างๆ (จาก dump file)
CREATE TABLE "public"."animal_numbers" (
    "animal_number_id" integer NOT NULL DEFAULT nextval('animal_numbers_animal_number_id_seq'::regclass),
    "number_code" varchar NOT NULL,
    "animal_name" varchar NOT NULL,
    "lottery_sub_type_id" integer NOT NULL,
    "notes" text,
    "created_at" timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
    "updated_at" timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
    PRIMARY KEY ("animal_number_id")
);

CREATE TABLE "public"."credit_transactions" (
    "id" uuid NOT NULL DEFAULT extensions.uuid_generate_v4(),
    "user_id" uuid,
    "amount" numeric NOT NULL,
    "transaction_type" text NOT NULL,
    "created_at" timestamptz DEFAULT now(),
    "description" text,
    "related_bill_number" text,
    PRIMARY KEY ("id")
);

CREATE TABLE "public"."delete_history" (
    "id" integer NOT NULL DEFAULT nextval('delete_history_id_seq'::regclass),
    "ticket_id" uuid NOT NULL,
    "user_id" uuid NOT NULL,
    "deleted_at" timestamp NOT NULL DEFAULT now(),
    "reason" text,
    PRIMARY KEY ("id")
);

CREATE TABLE "public"."drawing_schedules" (
    "schedule_id" integer NOT NULL DEFAULT nextval('drawing_schedules_schedule_id_seq'::regclass),
    "lottery_type_id" integer NOT NULL,
    "draw_time" time NOT NULL,
    "is_active" boolean NOT NULL DEFAULT true,
    "created_at" timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
    "lottery_sub_type_id" integer UNIQUE,
    "frequency_unit" varchar,
    "frequency_value" integer,
    "day_of_week" varchar,
    "open_time" time,
    "close_time" time,
    "updated_at" timestamptz DEFAULT now(),
    "cron_expression" varchar,
    PRIMARY KEY ("schedule_id")
);

CREATE TABLE "public"."house_percentages" (
    "id" integer NOT NULL DEFAULT nextval('house_percentages_id_seq'::regclass),
    "house_name" varchar NOT NULL,
    "percent1" numeric NOT NULL,
    "percent2" numeric NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "public"."line_users" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "user_id" varchar NOT NULL DEFAULT ''::character varying UNIQUE,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE TABLE "public"."login_history" (
    "id" integer NOT NULL DEFAULT nextval('login_history_id_seq'::regclass),
    "user_id" uuid,
    "email" text,
    "login_at" timestamptz DEFAULT now(),
    "ip_address" text,
    "user_agent" text,
    PRIMARY KEY ("id")
);

CREATE TABLE "public"."lottery_api_results" (
    "id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "draw_date" date NOT NULL,
    "draw_time" time,
    "country" text NOT NULL CHECK (country = ANY (ARRAY['LA'::text, 'VN'::text, 'MY'::text, 'STOCK'::text, 'OTHER'::text, 'TH'::text])),
    "lottery_name" text NOT NULL,
    "results" text[] NOT NULL,
    "source_url" text NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
    "updated_at" timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
    PRIMARY KEY ("id")
);

CREATE TABLE "public"."lottery_draws" (
    "id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "draw_date" date NOT NULL,
    "draw_time" time NOT NULL,
    "status" draw_status NOT NULL DEFAULT 'pending'::draw_status,
    "created_at" timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
    "updated_at" timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
    PRIMARY KEY ("id")
);

CREATE TABLE "public"."lottery_import_notifications" (
    "id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "notification_time" timestamptz NOT NULL,
    "lottery_names" text[] NOT NULL DEFAULT '{}'::text[],
    "total_results" integer NOT NULL DEFAULT 0,
    "message" text NOT NULL,
    "notification_type" text NOT NULL CHECK (notification_type = ANY (ARRAY['import_success'::text, 'import_error'::text])),
    "created_at" timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
    "updated_at" timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
    PRIMARY KEY ("id")
);

CREATE TABLE "public"."lottery_name_aliases" (
    "alias_id" integer NOT NULL DEFAULT nextval('lottery_name_aliases_alias_id_seq'::regclass),
    "lottery_sub_type_id" integer NOT NULL,
    "alias_name" varchar NOT NULL UNIQUE,
    "created_at" timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
    PRIMARY KEY ("alias_id")
);

CREATE TABLE "public"."lottery_notifications" (
    "id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "type" text NOT NULL CHECK (type = ANY (ARRAY['success'::text, 'error'::text, 'info'::text, 'warning'::text])),
    "message" text NOT NULL,
    "details" text,
    "timestamp" timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
    "draw_date" date NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
    "read_at" timestamptz,
    "is_read" boolean NOT NULL DEFAULT false,
    "data" jsonb,
    PRIMARY KEY ("id")
);

CREATE TABLE "public"."lottery_result_numbers" (
    "id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "lottery_result_id" bigint NOT NULL,
    "lottery_sub_type_id" integer NOT NULL,
    "numbers" text[] NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
    "updated_at" timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
    PRIMARY KEY ("id")
);

CREATE TABLE "public"."lottery_results" (
    "id" bigint NOT NULL DEFAULT nextval('lottery_results_v2_id_seq'::regclass),
    "lottery_type_id" integer NOT NULL,
    "lottery_sub_type_id" integer NOT NULL,
    "schedule_id" integer,
    "draw_date" date NOT NULL,
    "draw_time" time,
    "prize_code" text NOT NULL,
    "winning_number" text NOT NULL,
    "is_sent_to_line" boolean DEFAULT false,
    "created_at" timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
    "updated_at" timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
    PRIMARY KEY ("id")
);

CREATE TABLE "public"."lottery_send_notifications" (
    "id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "notification_time" timestamptz NOT NULL,
    "lottery_names" text[] NOT NULL DEFAULT '{}'::text[],
    "total_results" integer NOT NULL DEFAULT 0,
    "message" text NOT NULL,
    "notification_type" text NOT NULL CHECK (notification_type = ANY (ARRAY['send_success'::text, 'send_error'::text])),
    "created_at" timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
    "updated_at" timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
    PRIMARY KEY ("id")
);

CREATE TABLE "public"."lottery_sub_number" (
    "id" integer NOT NULL DEFAULT nextval('lottery_sub_number_id_seq'::regclass),
    "name" varchar NOT NULL,
    "description" text,
    "lottery_sub_type_id" integer NOT NULL,
    "length" integer,
    "created_at" timestamptz DEFAULT timezone('utc'::text, now()),
    "updated_at" timestamptz DEFAULT timezone('utc'::text, now()),
    "digit_number" integer,
    "type_number" varchar,
    "price_paid" numeric,
    PRIMARY KEY ("id")
);

COMMIT;
